version: '3.9'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: regintel-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/regintel123

      # Memory settings (adjust based on your machine)
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512m

      # APOC plugin (Advanced procedures)
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

      # Allow read-only connections
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*

      # Database settings
      NEO4J_dbms_default__database: regintel

    volumes:
      # Persist Neo4j data
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p regintel123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-import:
    driver: local
  neo4j-plugins:
    driver: local
